name: PolymarketEdge
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SWIFT_VERSION: 5.0
packages: {}
targets:
  PolymarketEdge:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.polymarket.edge
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
      properties:
        CFBundleName: PolymarketEdge
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIRequiredDeviceCapabilities:
          - arm64
schemes:
  PolymarketEdge:
    build:
      targets:
        PolymarketEdge: all
    run:
      config: Debug
