version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: polymarket-edge-api:dev
    container_name: polymarket-edge-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
