[tool.black]
line-length = 100
target-version = ["py311"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [
  ".git",
  "__pycache__",
  ".venv",
  "build",
  "dist",
]

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["app"]
asyncio_mode = "auto"
